### ISSUE TITLE
Packages moved to other repositories?

### ISSUE THREAD

**Issue by llrs** [cranhaven/cranhaven.r-universe.dev#3]
Nice idea!

Sometimes packages are moved from CRAN to Bioconductor (such as mixOmics). 
Would this be caught by the system? 
From what I found it doesn't compare with the registry on Bioconductor.

Last week, a new initiative started to use r-universe for giving maintainer some way to release packages to users. 
It is called [r-releases](https://github.com/r-releases), it doesn't have the same goals or purposes, but your input would be appreciated (We will discuss it on today's 2024/03/04 R repository working group meeting).

**Comment by HenrikBengtsson** [comment]
> > We will discuss it on today's 2024/03/04 R repository working group meeting
> 
> Turns out I no longer have access to those cal invites, so I don't have the zoom link to join. oh well...

Never mind, found it via an old email notification.

**Comment by llrs** [comment]
Let me know if it doesn't work I can send you the link

**Comment by HenrikBengtsson** [comment]
> Sometimes packages are moved from CRAN to Bioconductor (such as mixOmics).
> Would this be caught by the system?
> From what I found it doesn't compare with the registry on Bioconductor.

I literally coded this up over a beer and a bad TV show during this weekend's storm, and then I did lots of trial and errors to figure out how R-universe deals with different things. I first meant to only write up the idea as a proposal to Bioconductor for handling the coming-and-going packages on CRAN, but figured I could make a mockup on R-universe, and then it turned out to be not too hard to actually get it working.

The initial objective is for it to serve as a discussion point.  Things to discuss are:

* How long should packages stay on **CRANhaven** before being dropped (currently 4 weeks)?

* What should happen to packages that expire on **CRANhaven**? Should there we have a **CRANafterlife** too, where package are moved indefinitely?

* Should we treat packages that are archived on request of the maintainer differently from those archived by the CRAN Team?

* How to handle CRAN packages moved to Bioconductor?

* ...

**Comment by HenrikBengtsson** [comment]
Moving this topic to the general discussion thread at https://github.com/cranhaven/cranhaven.r-universe.dev/issues/4.
